export const LIST_FIN_RATIO = [
	"NIM (%)",
	"YEA (%)",
	"EPS (VND)",
	"P/B (Lần)",
	"Vốn hóa (VND)",
	"Hệ số CAR (%)",
	"Nợ phải trả (VND)",
	"Khe hở lãi suất (VND)",
	"Tỷ suất cổ tức (%)",
	"Chênh lệch lãi suất (%)",
	"Cổ tức tiền mặt (VND)",
	"Lợi nhuận sau thuế (VND)",
	"Thu nhập lãi thuần (YoY) (%)",
	"Lợi nhuận trước thuế (VND)",
	"Nợ nhạy cảm lãi suất (VND)",
	"Tỷ lệ cho vay/Huy động (LDR) (%)",
	"Tài sản nhạy cảm lãi suất (VND)",
	"Dòng tiền HĐKD/Lợi nhuận thuần (%)",
	"Chi phí lãi và chi phí tương tự (YoY) (%)",
	"Dòng tiền HĐKD/Trung bình tổng tài sản (%)",
	"Tỷ lệ cho vay trung dài hạn/Tổng dư nợ (%)",
	"Dự phòng cho vay khách hàng/Cho vay khách hàng (%)",
	"Cho vay xây dựng và kinh doanh bất động sản (YoY) (%)",
	"Dòng tiền HĐKD/Số lượng cổ phiếu đang lưu hành (VND)",
	"Dòng tiền hoạt động kinh doanh trên mỗi cổ phiếu (VND)"
]
