export const MAPPING_SKT_SAB = [
    { tk_no: 'tkkt' },
    { tk_co: 'tkdu' },
    { ps_no: 'tien_no' },
    { ps_co: 'tien_co' },
    { customer: 'customer' },
    { project: 'vu_viec_code' },
    { team_code: 'bo_phan_code' },
    { vender: 'customer' },
    { noiBo: 'noi_bo' },
    { employee: 'employee' },
    { consol: 'consol' },
    { product: 'product' },
    { day: 'day' },
    { month: 'month' },
    { year: 'year' },
    { diengiai: 'dien_giai' },
    { so_tien: 'so_tien_VND' },
    { supplier: 'supplier' },
    { kmf: 'kmf' },
    { kmns: 'kmns' },
    { unit_code: 'unit_code' },
    { hoaDon: 'hoa_don' },
    { hopDong: 'hop_dong' },
    { soChungTu: 'so_chung_tu' },
    { chuThich: 'chu_thich' },
    { company: 'company' },
];

export const MAPPING_VAS_SAB = [
    { ten_tai_khoan: 'code' },
    { ma_tai_khoan: 'code' },
    { phan_loai: 'phan_nhom' },
    { chu_thich_tai_khoan: 'HuongDanSuDung' },
    { t1_open_no: 'no_dau_ky' },
    { t1_open_co: 'co_dau_ky' },
    { company: 'company' },
    { year: 'year' },
];
