export const CARD = "Card"
export const Chain = "Chain"
export const TEMPLATE = "Template"
export const STEP = "Step"
export const SO_KE_TOAN_SAB = "SoKeToan"
export const INPUT = "Input"
export const CARD_INPUT = "CardInput"
export const NhaCungCap = "NhaCungCap"
export const KhachHang = "KhachHang"
export const DuAn = "DuAn"
export const HangHoa = "HangHoa"
export const Kmf = "Kmf"
export const Kmtc = "Kmtc"
export const HopDong = "HopDong"
export const KhoModel = "Kho"
export const KenhModel = "Kenh"
export const ChuongTrinh = "ChuongTrinh"
export const NhanVien = "NhanVien"
export const BusinessUnit = "BusinessUnit"
export const TaiKhoanNganHang = "TaiKhoanNganHang"
export const TaiKhoan = "TaiKhoan"
export const TaiSanDauTu = "TaiSanDauTu"
export const LoaiTien = "LoaiTien"
export const ChuSoHuu = "ChuSoHuu"
export const FileALL = "FileALL"
export const PhieuXuat = "PhieuXuat"
export const HoaDon = "HoaDon"



