export const LIST_FIN_RATIO = [
	"Tổng tài sản (VND)",
	"Vốn chủ sở hữu (VND)",
	"Nợ phải trả (VND)",
	"Vốn hóa (VND)",
	"Dòng tiền từ hoạt động kinh doanh (VND)",
	"Lợi nhuận sau thuế công ty mẹ (VND)",
	"ROE (%)",
	"ROA (%)",
	"ROIC (%)",
	"Biên lãi gộp (%)",
	"Biên lãi sau thuế (%)",
	"Vòng quay tồn kho (Lần)",
	"EPS (VND)",
	"P/E (Lần)",
	"BVPS (VND)",
	"P/B (Lần)",
	"P/S (Lần)",
	"Hệ số nợ trên vốn chủ sở hữu (%)",
	"Hệ số nợ trên tổng tài sản (%)",
	"Tỷ số thanh toán hiện hành (Lần)",
	"Tỷ số thanh toán nhanh (Lần)",
	"EBIT/Lãi vay (Lần)",
	"Cổ tức tiền mặt (VND)",
	"Tỷ suất cổ tức (%)",
	"Doanh thu thuần (YoY) (%)",
	"Lợi nhuận sau thuế CĐCTM (YoY) (%)",
	"Lợi nhuận từ HĐKD chính (YoY) (%)",
	"Tổng tài sản (YoY) (%)"
];
